mj:
  discord:
    guild-id: xxx
    channel-id: xxx
    user-token: xxx
    session-id: 94d15ef6d66a8c1361b07a8379c8ab1
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: baidu
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10
  baidu-translate:
    appid: xxx
    app-secret: xxx
    # proxy:
    #  host: 114.55.7.220
    # port: 20171
  aliyun:
    access-key-id: xxx
    access-key-secret: xxx
    uid: xxx
    oss-bucket: prod-midjourney
spring:
  redis:
    host: xxx
    port: 6379
    password: xxx
    timeout: 3000

